name: ">> Scheduled Code Analysis"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 0' # weekly, on Sunday at 07:00 UTC

jobs:
  code_analysis:
    name: Code Analysis (multi)
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/callable.code-analysis.yml
