name: "Send string to server"

on:
  workflow_dispatch:

jobs:
  testSendString:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Send string to server
        env:
          SERVER_URL: ${{ secrets.TEST_SERVER }}
          SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: |
          node scripts/sendString.js
